/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Oidc: () => import('#controllers/oidc_controller'),
  Session: () => import('#controllers/session_controller'),
}
